
export const PRODUCTS_REQUEST='ADD_PRODUCTS_REQUEST';

export const PRODUCTS_FAILURE='ADD_PRODUCTS_FAILURE';

//post

export const ADD_PRODUCTS_SUCCESS='ADD_PRODUCTS_SUCCESS';

//get

export const GET_PRODUCTS_SUCCESS='GET_PRODUCTS_SUCCESS';
