
export const PRODUCTS_DATA_REQUEST='PRODUCTS_DATA_REQUEST';
export const PRODUCTS_DATA_FAILURE='PRODUCTS_DATA_FAILURE';

export const GET_PRODUCTS_DATA='GET_PRODUCTS_DATA';
export const GET_PRODUCTS_EAT_WELL='GET_PRODUCTS_EAT_WELL'
export const GET_PRODUCTS_ELECTRONICS='GET_PRODUCTS_ELECTRONICS'