
export const PRODUCTS_DATA_REQUEST='PRODUCTS_DATA_REQUEST';
export const PRODUCTS_DATA_FAILURE='PRODUCTS_DATA_FAILURE';
export const GET_PRODUCTS_DATA='GET_PRODUCTS_DATA';

export const ADD_TO_CART_DATA='ADD_TO_CART_DATA';
